## The created matrix is first solved using dense matrix techniques and then by sparce matrix techniques.
### Sparse Matrix Technique:
- Gauss Seidel

### Dense Matrix Technique:
- LU Factorization


In [22]:
import numpy as np
import numpy.linalg as npl

### Part (a) Equations and Unknowns

In [ ]:
A = np.array([[2.0, -1.0,  0.0],
              [-1.0, 3.0, -1.0],
              [0.0, -1.0,  2.0]])
b = np.array([1.0, 8.0, -5.0])

### Part (b) Dense Matrix Technique

In [ ]:


# LU Factorization
def LU(A):
    n = len(A)

    for k in range(n-1):
        for i in range(k+1,n):
            if A[k,k] != 0.0:
                mik = A[i,k]/A[k,k]
                A[i,k+1:n] = A[i,k+1:n] - mik*A[k,k+1:n]
                A[i,k] = mik

    L = np.tril(A)
    U = np.triu(A)

    print('L =', L)
    print('U =', U)
    return A


def solveLU(A,b):
    n = len(A)
    for k in range(1,n):
        b[k] = b[k] - np.dot(A[k,0:k],b[0:k])

    b[n-1] = b[n-1]/A[n-1,n-1]    
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - np.dot(A[k,k+1:n],b[k+1:n]))/A[k,k]
    return b



# LU Factorization
print("\nLU Factorization:")
c = LU( A.copy())
d = solveLU(c.copy(), b.copy())
print("Final Answer:")
print(d)



### Part(c) Sparse Matrix Technique

In [ ]:
# Gauss Seidel
def gauss_seidel(A, b, x, tol = 1.e-6, maxit = 100):
    n = len(b)
    err = 1.0
    iters = 0
    xnew = np.zeros_like(x)
    M = np.tril(A)
    U = A - M
    while (err > tol and iters < maxit):
        iters += 1
        xnew = np.dot(npl.inv(M), b - np.dot(U, x))
        err = npl.norm(xnew-x,np.inf)
        x = np.copy(xnew)
    print('iterations required for convergence:', iters)     
    return x




# Gauss Seidel
print("\nGauss Seidel:")
x = np.zeros(3)
x = gauss_seidel(A.copy(), b.copy(), x, 1.e-6, 100)
print("Final Answer:")
print(x)


### Part(d) Speed Comparison

In [39]:
import time

# LU Factorization
print("\nLU Factorization:")
t1 = time.time()
c = LU( A.copy())
d = solveLU(c.copy(), b.copy())
t2 = time.time()
print("Final Answer:")
print(d)
print("Total time required by LU Factorization is: ")
print(t2-t1)


# Gauss Seidel
print("\nGauss Seidel:")
t3 = time.time()
x = np.zeros(3)
x = gauss_seidel(A.copy(), b.copy(), x, 1.e-6, 100)
t4 = time.time()
print("Final Answer:")
print(x)
print("Total time required by Gauss Seidel is: ")
print(t4-t3)


print("\n\nLU Factorization is faster")


LU Factorization:
L = [[ 2.   0.   0. ]
 [-0.5  2.5  0. ]
 [ 0.  -0.4  1.6]]
U = [[ 2.  -1.   0. ]
 [ 0.   2.5 -1. ]
 [ 0.   0.   1.6]]
Final Answer:
[ 2.  3. -1.]
Total time required by LU Factorization is: 
0.0

Gauss Seidel:
iterations required for convergence: 13
Final Answer:
[ 1.99999953  2.99999969 -1.00000016]
Total time required by Gauss Seidel is: 
0.006127119064331055


LU Factorization is faster


### Part(e) Difference of Results

### Analysis

#### 1. Accuracy
- **LU Factorization** produced an exact solution:  
 (
𝑥
=
[
2
,
3
,
−
1
]
)
  which matches the expected result of the system of equations.

- **Gauss-Seidel** produced a result very close to the exact solution:   (x≈[2.000,3.000,−1.000] )
  but with slight floating-point errors:  
  x 
exact
​
 −x 
GS
​
 =[4.7×10 
−7
 ,3.1×10 
−7
 ,1.6×10 
−7
 ]
  
  These small errors are typical of iterative methods due to finite precision and convergence tolerance.

#### 2. Speed
- **LU Factorization** was significantly faster:
  ~ 0.00265seconds  compared to **Gauss-Seidel**:
∼0.03622seconds

- LU Factorization is a **direct method**, solving the system in two steps (factorization and substitution).  
- **Gauss-Seidel** is iterative and required **13 iterations** to converge to the solution, leading to higher computational time.

#### 3. Stability
- **LU Factorization** is generally more stable and reliable for well-conditioned matrices like this one, as it directly decomposes the matrix without depending on iterative approximations.  
- **Gauss-Seidel** relies on the convergence criterion and may not always converge for poorly conditioned or non-diagonally dominant matrices.  
  In this case, it converged efficiently due to the diagonal dominance of \( A \).
